Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -37,12 +37,21 @@ jobs:
 
   adl-cicd-deploy-phase:
     if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
-    uses: AlightEngineering/adl-awsdeploy-cicd/.github/workflows/adl-cicd-deploy-repo-phase.yml@feature/workflowrefactor
-    secrets: inherit
-    with:
-      event_repo_name: ${{ github.repository }}
-      event_repo_branch: ${{ github.ref_name }}
-      deploy_env: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'prod' || github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.feature_branch_name, 'refs/heads/feature/' || 'error') && github.event.inputs.deploy_env || github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') && 'dev' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check feature branch name for workflow_dispatch
+        if: github_event_name == 'workflow_dispatch'
+        run: |
+          if [[ "${{ github.event.inputs.feature_branch_name }}" ! = feature/* ]]; then
+            echo "Error: The feature_branch_name is an invalid branch and must start with 'feature/'."
+            exit 1
+          fi
+      - name: Use ADL CICD Deployment Phase Action
+        uses: AlightEngineering/adl-awsdeploy-cicd/.github/workflows/adl-cicd-deploy-repo-phase.yml@feature/workflowrefactor
+        with:
+         event_repo_name: ${{ github.repository }}
+         event_repo_branch: ${{ github.ref_name }}
+         deploy_env: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'prod' || github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.feature_branch_name, 'refs/heads/feature/' || 'error') && github.event.inputs.deploy_env || github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') && 'dev' }}
       
   adl-log-event:
     runs-on: ubuntu-latest
