Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -1,6 +1,81 @@
-[root@cdp-datahub-dev1-gateway0 a1086139]# ps -ef | grep codedeploy
-root       863     1  0 Nov03 ?        00:00:06 codedeploy-agent: master 863
-root      2991   863  0 Nov03 ?        00:00:39 codedeploy-agent: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 863
-root     21368  2991  0 02:04 ?        00:00:00 sh /opt/codedeploy-agent/deployment-root/df29ca74-bc69-4591-90c0-5f6bc57ba083/d-9YNJT2TN2/deployment-archive/hookscripts/afterinstall.sh
-root     27733 27074  0 02:09 pts/33   00:00:00 grep --color=auto codedeploy
-[root@cdp-datahub-dev1-gateway0 a1086139]#
+#!/bin/bash
+chown adl_dev_all_mig_svc:adl_all_mig /apps/dataproduct/cases
+chmod -R 755 /apps/dataproduct/cases
+chown -R adl_dev_all_mig_svc:adl_all_mig /apps/dataproduct/cases/adl-cases-hrxassist-etl
+
+ls -al /apps/dataproduct/cases/adl-cases-hrxassist-etl
+sudo -i -u adl_dev_all_mig_svc mkdir /apps/dataproduct/cases/adl-cases-hrxassist-etl/1.0.71
+sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
+sudo -i -u adl_dev_all_mig_svc tar -xvf /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/adl-cases-hrxassist-etl-1.0.71.tar --directory /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
+
+AUTO_INFLATE_FLAG=True
+if [[ ${AUTO_INFLATE_FLAG} != "True" ]]; then
+  exit 0
+else	
+  cd /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
+  
+  # CI/CD should not create the top-level directories; this needs to be done at EC2 provisioning time.
+  if [[ -d "/apps/edh/prod" && -d "/apps/ben" ]]; then
+    ls -al /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
+
+    for install_path in $(find . -type f); do
+      # Separate the TAR entry into its file name and file path parts.
+      install_file=$(echo ${install_path##*/})
+      install_directory=$(echo ${install_path%/*} | cut -c3- )
+
+      # Check if the file or directory already exists, if yes, ignore and proceed to the next iteration.
+      if [ -e "/apps/${install_directory}/${install_file}" ]; then
+        echo "File/directory already exists: /apps/${install_directory}/${install_file}. Skipping..."
+        continue
+      fi
+
+      # Create the subdirectory where the file will be copied. Create all required parent directories, and exit if there is an error in directory creation.
+      echo $install_path
+      echo "ceating this directory /apps/$install_directory"
+      echo "sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/${install_directory}"
+      sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/${install_directory}
+      chmod -R 755 /apps/${install_directory}
+      if [[ $? -ne "0" ]]; then
+        echo "Could not create directory: /apps/${install_directory}"
+        exit 1
+      fi
+
+      # Update group for nested directories.
+      update_grp_dir="/apps"
+      for subdir in $(echo ${install_directory} | tr "/" " "); do
+        if [[ ${update_grp_dir} != "/apps" && ${update_grp_dir} != "/apps/edh" && ${update_grp_dir} != "/apps/edh/prod" && ${update_grp_dir} != "/apps/ben" ]]; then
+          chgrp adl_all_mig ${update_grp_dir}
+          if [[ $? -ne "0" ]]; then
+            echo "Could not chgrp to: adl_all_mig on ${update_grp_dir}"
+            exit 1
+          fi
+        fi
+        update_grp_dir=${update_grp_dir}/${subdir}
+      done
+
+      # Copy the file into its target directory, update the group on the new file.
+      sudo -i -u adl_dev_all_mig_svc cp /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage/${install_directory}/${install_file} /apps/${install_directory}/${install_file} && \
+      chgrp adl_all_mig /apps/${install_directory}/${install_file} && \
+      chmod 755 /apps/${install_directory}/${install_file}
+      
+      if [[ $? -ne "0" ]]; then
+        echo "Could not write file to: /apps/${install_directory}/${install_file}"
+        exit 1
+      fi
+
+      # If the target directory contains either bin or scripts, make the copied file executable.
+      if [[ ${install_path} == *"bin/"* || ${install_path} == *"scripts/"* ]]; then
+        sudo -i -u adl_dev_all_mig_svc chmod +x /apps/${install_directory}/${install_file}
+      fi
+    done
+
+    cd /apps/dataproduct/cases/adl-cases-hrxassist-etl/land
+    rm -rf stage
+    cp -i /opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log /tmp/codedeploy-agent-deployments.log
+    chmod 755 /tmp/codedeploy-agent-deployments.log
+    chown  adl_dev_all_mig_svc:adl_all_mig /tmp/codedeploy-agent-deployments.log
+  else
+    echo "Error: Required top-level directories, /apps and /apps/edh/prod, do not exist. Please review the setup of the instance on which this deployment was attempted."
+    exit 1
+  fi
+fi
