Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -1,15 +1,13 @@
- adl-log-event:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Default
-        run: |
-          echo ${{ github.event_name }}
-          if: github.event_name == 'workflow_dispatch'
-          runs-on: ubuntu-latest
-          steps:
-            - name: check feature_branch_name for workflow_dispatch
-              run: |
-                if [[ "${{ github.event.inputs.feature_branch_name }}" != feature/* ]]; then
-                  echo "Error: The feature_branch_name is an invalid branch and must start with 'feature/'."
-                  exit 1
-                fi
+adl-log-event:
+  runs-on: ubuntu-latest
+  steps:
+    - name: Echo Event Name
+      run: echo ${{ github.event_name }}
+
+    - name: Check feature_branch_name for workflow_dispatch
+      if: github.event_name == 'workflow_dispatch'
+      run: |
+        if [[ "${{ github.event.inputs.feature_branch_name }}" != feature/* ]]; then
+          echo "Error: The feature_branch_name is an invalid branch and must start with 'feature/'."
+          exit 1
+        fi
