Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -1,43 +1,18 @@
-import json
-from alight.foundation.util.logging.standardlogger import StandardLogger
-from alight.foundation.redshift.datapi import DataAPI
-
-class RedshiftSchemaToJSON:
-    logger = StandardLogger().getDefaultLogger()
-
-    def __init__(self, data_api):
-        self.data_api = data_api
-
-    def get_object_schema(self, database_name, schema_name, object_name, object_type):
-        try:
-            if object_type not in ["TABLE", "VIEW"]:
-                raise ValueError("Unsupported object type. Only 'TABLE' or 'VIEW' are supported.")
-            
-            response = self.data_api.describe_table(
-                DatabaseName=database_name,
-                Schema=schema_name,
-                TableName=object_name,
-                DbUser=self.data_api._db_user_name
-            )
-            
-            object_schema = {
-                "Database": database_name,
-                "Schema": schema_name,
-                "ObjectName": object_name,
-                "ObjectType": object_type,
-                "Fields": []
-            }
-            
-            for column in response['Table']['Columns']:
-                field = {
-                    "FieldName": column['Name'],
-                    "FieldType": column['Type'],
-                    "FieldPrecision": column.get('Precision', None),
-                    "EncodingCompression": column.get('Encoding', None)
-                }
-                object_schema['Fields'].append(field)
-            
-            return json.dumps(object_schema, indent=4)
-        except Exception as e:
-            RedshiftSchemaToJSON.logger.error(str(e))
-            raise
+name: Sonarqube Analysis
+jobs:
+  sonarqube-check:
+    image: sonarsource/sonar-scanner-cli:latest
+  variables:
+    SONAR_TOKEN: $SONAR_TOKEN
+    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
+  script:
+    - sonar-scanner -Dsonar.host.url=https://sonarqube.example.com -Dsonar.login=$SONAR_TOKEN
+    - sonar_status=$?
+    - if [ $sonar_status -eq 0 ]; then
+        echo "Sonar analysis completed successfully";
+      else
+        echo "Sonar analysis failed or had issues";
+        exit 1;
+      fi
+  only:
+    - merge_requests
