Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -1,14 +1,75 @@
+# DO NOT MODIFY OR DELETE THIS WORKFLOW!!
+
+name: ADL CICD Deployment Pipeline
+
+on:
+  pull_request:
+    branches: [ master ]
+    types: [opened, reopened, edited]
+  push:
+    branches: [master, feature/*, hotfix/* ]
+    paths-ignore:
+      - '.version'
+      - '.github/**'
+      - 'Explore/**'
+      - 'README.md'
+      - 'CODEOWNERS'
+      - '.group'
+  workflow_dispatch:
+    inputs:
+      deploy_env:
+        description: 'Deployment Environment (e.g., qa, qc)'
+        required: true
+        type: choice
+        options:
+          - 'qa'
+          - 'qc'    
+      feature_branch_name:
+        description: 'Enter the branch (e.g., feature/your-branch-name)'
+        required: true
+        default: 'feature/your-branch-name'  
 jobs:
-  adl-cicd-hotfix:
+  adl-cicd-check-pull-request:
+    if: github.event_name == 'pull_request'
+    uses: AlightEngineering/adl-awsdeploy-cicd/.github/workflows/adl-cicd-check-pull-request.yml@feature/workflowrefactor
+    secrets: inherit
+
+  adl-cicd-deploy-phase:
+    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/hotfix/') != true )|| (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.feature_branch_name, 'feature/'))
+    uses: AlightEngineering/adl-awsdeploy-cicd/.github/workflows/adl-cicd-deploy-repo-phase.yml@feature/workflowrefactor
+    secrets: inherit
+    with:
+      event_repo_name: ${{ github.repository }}
+      event_repo_branch: ${{ github.ref_name }}
+      deploy_env: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'prod' || github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_env || github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') && 'dev' }}
+
+  adl-cicd-hotfix-approval:
     if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/hotfix/')
     runs-on: ubuntu-latest
     steps:
-      - name: Wait for Deployment Approval
+      - name: Await Hotfix Deployment Approval
         uses: actions/wait-for-deployment-approval@v1
         with:
           environment: hotfix
           
-      - name: Deploy Hotfix
+  adl-cicd-hotfix-phase:
+    needs: [adl-cicd-hotfix-approval]
+    uses: AlightEngineering/adl-awsdeploy-cicd/.github/workflows/adl-cicd-deploy-repo-phase.yml@feature/workflowrefactor
+    secrets: inherit
+    with:
+      event_repo_name: ${{ github.repository }}
+      event_repo_branch: ${{ github.ref_name }}
+      deploy_env: prod
+
+  adl-log-event:
+    runs-on: ubuntu-latest
+    steps:
+      - name: GitHub Event Name
+        run: echo ${{ github.event_name }}
+      - name: Check Feature Branch 
+        if: github.event_name == 'workflow_dispatch'
         run: |
-          echo "Deploying hotfix..."
-          # Insert your deployment commands here
+          if [[ "${{ github.event.inputs.feature_branch_name }}" != feature/* ]]; then
+            echo "Error: The feature_branch_name is an invalid branch and must start with 'feature/'."
+            exit 1
+          fi
