Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -1,49 +1,118 @@
-name: ADL CICD Checkout Postgres Phase
-
+name: ADL Deploy Postgres Artifacts
 on:
-  workflow_call:
-    secrets:
-      envPAT:
-        required: true
-    inputs:
-      cicd_version:
-        description: 'CICD Stable Release Version'
-        type: string
-        required: false
-        default: 'd1.0.285'
-
+  repository_dispatch:
+    types:
+      - adl-postgres-deploy
 jobs:
-  adl-checkout-calling-repo:
-    runs-on: [self-hosted, devops-control-prod]
-
+  adl-postgres-deploy:
+    env:
+      event_repo_name: ${{ github.event.client_payload.name }}
+      cicd_version: ${{ github.event.client_payload.cicd_version }}
+      event_repo_branch: ${{ github.event.client_payload.branch }}
+      calling_repo_name: ${{ github.event.repository.full_name }}
+      dispatch_repo_name: ${{ 'adl-awsdeploy-cicd' }}
+    runs-on:  [self-hosted, devops-control-prod]
     steps:
-    - name: Debug
-      run: |
-        pwd
-        ls -al
+      - name: Log Environment Variables
+        run: |
+          echo "This is the Repo to deploy: ${event_repo_name}"
+          echo "This is the stable repo release version to deploy: ${cicd_version}"
+          echo "This is the Repo that made the request: ${calling_repo_name}"
+          echo "This is the Version Of CICD being used: ${calling_repo_name}-${cicd_version}"
 
-    - name: Checkout Repository
-      uses: actions/checkout@master
+      - name: Check Calling Repository
+        run: |
+          calling_repo_base_name=${calling_repo_name##*/}
+          if [[ ${calling_repo_base_name} != ${dispatch_repo_name} ]]
+          then
+            echo "adl-aws-deploy called from invalid origin, fail and exit"
+            exit 1
+          fi
+      - name: Get Requesting Repository
+        env:
+          github_user: ${{ secrets.GH_USER_NAME }}
+          github_token: ${{ secrets.GH_CLONE_REPO }}
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          echo "This is versioned_calling_repo_base_name: ${versioned_calling_repo_base_name}"
+          rm -rf ${versioned_calling_repo_base_name} ${event_repo_name}
+          git clone --single-branch --depth=1 --branch=${cicd_version} https://${github_user}:${github_token}@github.com/${calling_repo_name}.git ${versioned_calling_repo_base_name}
+          git clone --single-branch --depth=1 --branch=${event_repo_branch} https://${github_user}:${github_token}@github.com/${event_repo_name}.git
+      - name: Increment Calling Repo Version
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          event_repo_base_name=${event_repo_name##*/}
+          source ${versioned_calling_repo_base_name}/scripts/.mdshrc
+          mdsh_init ${event_repo_branch} local adl ${event_repo_base_name} localhost
+          git config --global user.email "dushyant.remivasan@alight.com"
+          git config --global user.name "Dushyant Remivasan"
+          if [[ "${mdsh_env}" = "dev" ]]
+          then
+            bump_version patch ${event_repo_base_name}
+            git -C ${event_repo_base_name} add .version
+            git -C ${event_repo_base_name} commit -m "Increments Version"
+            git -C ${event_repo_base_name} push
+          fi
+          new_git_tag=$(version ${event_repo_base_name})
+          gtag_version ${event_repo_base_name} ${mdsh_env} ${new_git_tag} "CICD Pipeline Merge To ${event_repo_branch}"
+      - name: ADL Set Environment Credentials
+        id: adl-set-env-creds
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          source ${versioned_calling_repo_base_name}/config/.cicdrc ${event_repo_branch}
+          echo "aws_access_key_id_name=ADL_${credential_env}_ACCESS_KEY" >> $GITHUB_OUTPUT
+          echo "aws_secret_access_key_name=ADL_${credential_env}_SECRET_KEY" >> $GITHUB_OUTPUT
 
-    - name: Checkout Requesting Repository Branch
-      run: |
-        echo "Checking out Repository: $GITHUB_REPOSITORY"
-        echo "Checking out Branch: $GITHUB_REF_NAME"
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1-node16
+        env:
+          AWS_ACCESS_KEY_ID_NAME: ${{ steps.adl-set-env-creds.outputs.aws_access_key_id_name }}
+          AWS_SECRET_ACCESS_KEY_NAME: ${{ steps.adl-set-env-creds.outputs.aws_secret_access_key_name }}
+        with:
+          aws-access-key-id: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
+          aws-secret-access-key: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
+          aws-region: us-east-1
+      - name: Install Dependencies
+        run: |
+          apt-get install python-pip
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          echo "Installing dependencies from ${versioned_calling_repo_base_name}/requirements.txt"
+          pip install -r ${versioned_calling_repo_base_name}/requirements.txt
+      - name: Run CICD Pipeline
+        env:
+          POSTGRES_DB_USER_NAME: ${{ secrets.POSTGRES_DB_USER_NAME }}
+          POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
+        run: |
+          versioned_calling_repo_base_name=${calling_repo_name}-${cicd_version}
+          export BUILD_NUMBER=${{ github.run_number }}
+          event_repo_base_name=${event_repo_name##*/}
+          export PYTHONPATH=${PWD}/${versioned_calling_repo_base_name}/src:${PWD}/${event_repo_base_name}/src/:$PYTHONPATH
+          source ${versioned_calling_repo_base_name}/scripts/.mdshrc
+          adl_postgres_cicd ${event_repo_branch} ${event_repo_base_name} ${versioned_calling_repo_base_name}
 
-    - name: Show Repository and Branch Info
-      run: |
-        echo "Checking out Repository: $GITHUB_REPOSITORY"
-        echo "Checking out Branch: $GITHUB_REF_NAME"
 
-  adl-dispatch-postgres-deploy-workflow:
-    needs:
-      - adl-checkout-calling-repo
-    runs-on: [self-hosted, devops-control-prod]
+Getting error at the requesting repository stage
 
-    steps:
-    - name: Trigger Postgres Deploy
-      run: |
-        curl -X POST https://api.github.com/repos/AlightEngineering/adl-awsdeploy-cicd/dispatches \
-          -H "Authorization: Bearer ${{ secrets.envPAT }}" \
-          -H 'Accept: application/vnd.github.everest-preview+json' \
-          --data '{"event_type": "adl-postgres-deploy", "client_payload": { "name": "'"$GITHUB_REPOSITORY"'", "branch": "'"$GITHUB_REF_NAME"'", "cicd_version": "${{ inputs.cicd_version }}" }'
+1s
+Run versioned_calling_repo_base_name=$***calling_repo_name***-$***cicd_version***
+This is versioned_calling_repo_base_name: AlightEngineering/adl-awsdeploy-cicd-d1.0.285
+Cloning into 'AlightEngineering/adl-awsdeploy-cicd-d1.0.285'...
+Note: switching to '8824a44b1fa65af8c3756c727e0a9e1f3ff0c9ef'.
+
+You are in 'detached HEAD' state. You can look around, make experimental
+changes and commit them, and you can discard any commits you make in this
+state without impacting any branches by switching back to a branch.
+
+If you want to create a new branch to retain commits you create, you may
+do so (now or later) by using -c with the switch command. Example:
+
+  git switch -c <new-branch-name>
+
+Or undo this operation with:
+
+  git switch -
+
+Turn off this advice by setting config variable advice.detachedHead to ***
+
+fatal: destination path 'adl-postgres-poc' already exists and is not an empty directory.
+Error: Process completed with exit code 128.
