Update builspectkuckingkar

diff --git a/builspectkuckingkar b/builspectkuckingkar
--- a/builspectkuckingkar
+++ b/builspectkuckingkar
@@ -1,96 +1,104 @@
-2023-11-07 03:12:50 [stderr]cp: overwrite ‘/tmp/codedeploy-agent-deployments.log’?
 
 
 #!/bin/bash
+SOURCE_DIR="/apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage"
+DEST_DIR="/apps"
 chown adl_dev_all_mig_svc:adl_all_mig /apps/dataproduct/cases
 chmod -R 755 /apps/dataproduct/cases
 chown -R adl_dev_all_mig_svc:adl_all_mig /apps/dataproduct/cases/adl-cases-hrxassist-etl
 
 ls -al /apps/dataproduct/cases/adl-cases-hrxassist-etl
-sudo -i -u adl_dev_all_mig_svc mkdir /apps/dataproduct/cases/adl-cases-hrxassist-etl/1.0.71
+sudo -i -u adl_dev_all_mig_svc mkdir /apps/dataproduct/cases/adl-cases-hrxassist-etl/1.0.78
 sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
-sudo -i -u adl_dev_all_mig_svc tar -xvf /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/adl-cases-hrxassist-etl-1.0.71.tar --directory /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
-
+sudo -i -u adl_dev_all_mig_svc tar -xvf /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/adl-cases-hrxassist-etl-1.0.78.tar --directory /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
 AUTO_INFLATE_FLAG=True
-if [[ ${AUTO_INFLATE_FLAG} != "True" ]]; then
+if [[ ${AUTO_INFLATE_FLAG} != "True" ]]
+then
   exit 0
-else	
+else
   cd /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
-  
-  # CI/CD should not create the top-level directories; this needs to be done at EC2 provisioning time.
-  if [[ -d "/apps/edh/prod" && -d "/apps/ben" ]]; then
-    ls -al /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
+  # CI/CD should not create the top-level directories, this needs to be done at EC2 provisioning time..
+  if [[ -d "/apps/edh/prod" && -d "/apps/ben" ]]
+  then
+      ls -al /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage
 
-    for install_path in $(find . -type f); do
-      # Separate the TAR entry into its file name and file path parts.
-      install_file=$(echo ${install_path##*/})
-      install_directory=$(echo ${install_path%/*} | cut -c3- )
-
-      # Check if the file or directory already exists, if yes, ignore and proceed to the next iteration.
-      if [ -e "/apps/${install_directory}/${install_file}" ]; then
-        echo "File/directory already exists: /apps/${install_directory}/${install_file}. Skipping..."
-        continue
-      fi
-
-      # Create the subdirectory where the file will be copied. Create all required parent directories, and exit if there is an error in directory creation.
-      echo $install_path
-      echo "ceating this directory /apps/$install_directory"
-      echo "sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/${install_directory}"
-      sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/${install_directory}
-      chmod -R 755 /apps/${install_directory}
-      if [[ $? -ne "0" ]]; then
-        echo "Could not create directory: /apps/${install_directory}"
-        exit 1
-      fi
-
-      # Update group for nested directories.
-      update_grp_dir="/apps"
-      for subdir in $(echo ${install_directory} | tr "/" " "); do
-        if [[ ${update_grp_dir} != "/apps" && ${update_grp_dir} != "/apps/edh" && ${update_grp_dir} != "/apps/edh/prod" && ${update_grp_dir} != "/apps/ben" ]]; then
-          chgrp adl_all_mig ${update_grp_dir}
-          if [[ $? -ne "0" ]]; then
-            echo "Could not chgrp to: adl_all_mig on ${update_grp_dir}"
-            exit 1
-          fi
+      for install_path in $(find . -type f)
+      do
+        # Separate the TAR entry into its file name and file path parts.
+        install_file=$(echo ${install_path##*/})
+        install_directory=$(echo ${install_path%/*} | cut -c3- )
+        # Create the subdirectory where the file will be copied. Create all required
+        # parent directories, and exit if there is an error in directory creation
+        # create the directories as the migration id, NOT as root, which yields a default 755 permission set.
+	if [ -e "${DEST_DIR}/${install_directory}/${install_file}" ];
+	then
+	  source_checksum=$(md5sum "${SOURCE_DIR}/${install_directory}/${install_file}" | awk '{print $1}')
+	  dest_checksum=$(md5sum "${DEST_DIR}/${install_directory}/${install_file}" | awk '{print $1}')
+          if [ "${source_checksum}" = "${dest_checksum}" ];
+          then
+	    echo "File unchanged: ${DEST_DIR}/${install_directory}/${install_file}. Skipping ..."
+	    continue
+	  fi
+	fi
+        echo $install_path
+        echo "creating this directory /apps/$install_directory"
+        echo "sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/${install_directory}"
+        sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/${install_directory}
+        chmod -R 755 /apps/${install_directory}
+        if [[ $? -ne "0" ]]
+        then
+          echo "Could not create directory: /apps/${install_directory}"
+          exit 1
         fi
-        update_grp_dir=${update_grp_dir}/${subdir}
+	update_grp_dir="/apps"
+        # Split the created directory into its distinct directory parts, as
+        # as each of these nested directories will need to have its
+        # group updated to the migration id's group. By default the group is not the correct migration id's group.
+        for subdir in $(echo ${install_directory} | tr "/" " ")
+        do
+          if [[ ${update_grp_dir} == "" ]]
+          then
+            update_grp_dir=${subdir}
+          else
+            update_grp_dir=${update_grp_dir}/${subdir}
+          fi
+          # Skip if the directory part is one of the base directories.
+          if [[ ${update_grp_dir} == "/apps" || ${update_grp_dir} == "/apps/edh" || ${update_grp_dir} == "/apps/edh/prod" || ${update_grp_dir} == "/apps/ben" ]]
+          then
+            echo "Base Directories, no action"
+          else
+            chgrp adl_all_mig ${update_grp_dir}
+            if [[ $? -ne "0" ]]
+            then
+              echo "Could not chgrp to: adl_all_mig on ${update_grp_dir}"
+              exit 1
+            fi
+          fi
+        done
+
+        # Copy the file into its target directory, update the group on the new file.
+        sudo -i -u adl_dev_all_mig_svc cp /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage/${install_directory}/${install_file} /apps/${install_directory}/${install_file} && \
+          chgrp adl_all_mig /apps/${install_directory}/${install_file} && \
+          chmod 755 /apps/${install_directory}/${install_file}
+        if [[ $? -ne "0" ]]
+        then
+          echo "Could not write file to: /apps/${install_directory}/${install_file}"
+          exit 1
+        fi
+        # If the target directory contains either bin or scripts, make the copied file executable
+        if [[ ${install_path} == *"bin/"* || ${install_path} == *"scripts/"* ]]
+        then
+          sudo -i -u adl_dev_all_mig_svc chmod +x /apps/${install_directory}/${install_file}
+
+        fi
       done
-
-      # Copy the file into its target directory, update the group on the new file.
-      sudo -i -u adl_dev_all_mig_svc cp /apps/dataproduct/cases/adl-cases-hrxassist-etl/land/stage/${install_directory}/${install_file} /apps/${install_directory}/${install_file} && \
-      chgrp adl_all_mig /apps/${install_directory}/${install_file} && \
-      chmod 755 /apps/${install_directory}/${install_file}
-      
-      if [[ $? -ne "0" ]]; then
-        echo "Could not write file to: /apps/${install_directory}/${install_file}"
-        exit 1
-      fi
-
-      # If the target directory contains either bin or scripts, make the copied file executable.
-      if [[ ${install_path} == *"bin/"* || ${install_path} == *"scripts/"* ]]; then
-        sudo -i -u adl_dev_all_mig_svc chmod +x /apps/${install_directory}/${install_file}
-      fi
-    done
-
-    cd /apps/dataproduct/cases/adl-cases-hrxassist-etl/land
-    rm -rf stage
-    cp -i /opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log /tmp/codedeploy-agent-deployments.log
-    chmod 755 /tmp/codedeploy-agent-deployments.log
-    chown  adl_dev_all_mig_svc:adl_all_mig /tmp/codedeploy-agent-deployments.log
+      cd /apps/dataproduct/cases/adl-cases-hrxassist-etl/land
+      rm -rf stage
+      cp -f /opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log /tmp/codedeploy-agent-deployments.log
+      chmod 755 /tmp/codedeploy-agent-deployments.log
+      chown  adl_dev_all_mig_svc:adl_all_mig /tmp/codedeploy-agent-deployments.log
   else
-    echo "Error: Required top-level directories, /apps and /apps/edh/prod, do not exist. Please review the setup of the instance on which this deployment was attempted."
+    echo "Error: Required top level directories, /apps and /apps/edh/prod, do not exist. Please review the setup of the instance on which this deployment was attemmpted."
     exit 1
   fi
 fi
-
-
-2023-11-08 01:45:38 [stdout]File unchanged: /apps/edh/prod/discovery/operational_event/bin/load_edh_discovery_assist_case_summary_2.scala. Skipping ...
-2023-11-08 01:45:38 [stdout]./edh/prod/discovery/operational_event/bin/load_edh_discovery_assist_case_detail_test.jar
-2023-11-08 01:45:38 [stdout]creating this directory /apps/edh/prod/discovery/operational_event/bin
-2023-11-08 01:45:38 [stdout]sudo -i -u adl_dev_all_mig_svc mkdir -p /apps/edh/prod/discovery/operational_event/bin
-2023-11-08 01:45:43 [stdout]Base Directories, no action
-2023-11-08 01:45:43 [stdout]Base Directories, no action
-2023-11-08 01:45:43 [stdout]File unchanged: /apps/edh/prod/discovery/operational_event/bin/load_edh_discovery_assist_attribute_detail_1.scala. Skipping ...
-2023-11-08 01:45:44 [stdout]File unchanged: /apps/edh/prod/discovery/operational_event/bin/truncate_baseline_acd_parallel.sh. Skipping ...
-2023-11-08 01:45:44 [stdout]File unchanged: /apps/edh/prod/discovery/operational_event/bin/load_edh_discovery_case_detail_assist_data_union.sh. Skipping ...
-
